
f = open('entrada.txt')
text_entrada = f.read()
f.close()

text_sortida = text_entrada.replace("∆", "e") 
text_sortida = text_sortida.replace("∕", "t") 
text_sortida = text_sortida.replace("∂", "a") 
text_sortida = text_sortida.replace("∊", "i") 
text_sortida = text_sortida.replace("∐", "o") 
text_sortida = text_sortida.replace("∏", "n") 
text_sortida = text_sortida.replace("∔", "s") 
text_sortida = text_sortida.replace("∓", "r") 
text_sortida = text_sortida.replace("∉", "h") 
text_sortida = text_sortida.replace("∍", "l") 
text_sortida = text_sortida.replace("∅", "d") 
text_sortida = text_sortida.replace("∄", "c") 
text_sortida = text_sortida.replace("∖", "u") 
text_sortida = text_sortida.replace("∎", "m") 
text_sortida = text_sortida.replace("∇", "f") 
text_sortida = text_sortida.replace("∑", "p") 
text_sortida = text_sortida.replace("∈", "g") 
text_sortida = text_sortida.replace("∀", "y") 
text_sortida = text_sortida.replace("∘", "w") 
text_sortida = text_sortida.replace("∃", "b") 
text_sortida = text_sortida.replace("∌", "k") 
text_sortida = text_sortida.replace("∋", "j") 
text_sortida = text_sortida.replace("∁", "z") 
text_sortida = text_sortida.replace("∗", "v") 
text_sortida = text_sortida.replace("−", "q") 
text_sortida = text_sortida.replace("∙", "x") 

f = open('sortida.txt','w')
f.write(text_sortida)
f.close()
